### ISSUE TITLE
Typescript highlighting

### ISSUE THREAD

**Issue by waldnercharles** [Rozbo/papercolor-vscode#1]
It appears that keywords in Typescript have no highlighting. Is this intentional?

![image](https://cloud.githubusercontent.com/assets/1673181/22469990/0bf346a0-e78b-11e6-9221-ae99bcee5713.png)

**Comment by ohroy** [comment]
Sorry,this theme does not support `ts` now. 
I will take time to update it

**Comment by ohroy** [comment]
yes! yes!
